# Generated by Django 5.2.5 on 2025-08-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_yield_liters', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('evening_yield_liters', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_yield_liters', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='livestock.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='farms.farmer')),
            ],
        ),
    ]
