# Generated by Django 5.2.5 on 2025-08-23 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_tag', models.CharField(max_length=50, unique=True)),
                ('breed', models.CharField(choices=[('LOCAL', 'Local Breed'), ('HOLSTEIN', 'Holstein'), ('JERSEY', 'Jersey'), ('ANGUS', 'Angus'), ('BRAHMAN', 'Brahman'), ('CROSSBRED', 'Crossbred'), ('OTHER', 'Other')], default='LOCAL', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('mother_tag', models.CharField(blank=True, help_text="Mother's tag ID if known", max_length=50)),
                ('source', models.CharField(choices=[('born', 'Born on farm'), ('purchased', 'Purchased')], default='born', help_text='Indicates if the cow was born on the farm or purchased', max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='farms.farm')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cows', to='farms.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='CowActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('VACCINATION', 'Vaccination'), ('HEALTH_CHECK', 'Health Check'), ('BREEDING', 'Breeding'), ('BIRTH', 'Birth'), ('TREATMENT', 'Medical Treatment'), ('HOOF_CARE', 'Hoof Care'), ('WEIGHT_CHECK', 'Weight Check'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('veterinarian', models.CharField(blank=True, max_length=100)),
                ('medication_used', models.CharField(blank=True, max_length=200)),
                ('next_due_date', models.DateField(blank=True, help_text='When this activity should be repeated', null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('is_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.cow')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farmer')),
            ],
        ),
    ]
